name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "zczc.men"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "exmaple.com"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.zczc.men", custom_domain = true },
  { pattern = "quay.zczc.men", custom_domain = true },
  { pattern = "gcr.zczc.men", custom_domain = true },
  { pattern = "k8s-gcr.zczc.men", custom_domain = true },
  { pattern = "k8s.zczc.men", custom_domain = true },
  { pattern = "ghcr.zczc.men", custom_domain = true },
  { pattern = "cloudsmith.zczc.men", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.zczc.men", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
